import React, { useEffect, useState } from "react";
import { PageHeader } from "../../components/layout/PageHeader";
import {
  Card,
  CardHeader,
  CardTitle,
  CardContent,
} from "@/components/ui/card";

import {
  Sparkles,
  Leaf,
  ShieldCheck,
  AlertTriangle,
  FlaskConical,
  ExternalLink,
  Info,
} from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

import api from "@/services/api";
import { fetchHealthScoreApi } from "@/services/patientService";


export const HerbalRecommendationsPage = () => {

  const [herbs, setHerbs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const [safetyNote, setSafetyNote] = useState("");
  const [dataAttribution, setDataAttribution] = useState("");

  useEffect(() => {

    const loadHerbalRecommendations = async () => {

      try {

        setLoading(true);
        setError(null);

        /*
         * Get the Prakriti result generated by the
         * backend Prakriti scoring endpoint.
         */
        const savedPrakriti = localStorage.getItem(
          "mediguard_prakriti_result"
        );

        const prakriti = savedPrakriti
          ? JSON.parse(savedPrakriti)
          : null;


        /*
         * Herbal recommendations are personalized
         * according to the user's primary Dosha.
         */
        if (!prakriti?.primary_dosha) {

          setError(
            "Please complete the Prakriti Quiz first."
          );

          return;
        }


        /*
         * Get the patient's current health-risk levels.
         */
        let diabetesRisk = "moderate";
        let cvdRisk = "moderate";

        try {

          const healthScore =
            await fetchHealthScoreApi();

          diabetesRisk =
            healthScore?.diabetesRiskLevel ||
            "moderate";

          cvdRisk =
            healthScore?.cvdRiskLevel ||
            "moderate";

        } catch (healthError) {

          console.warn(
            "Could not load health risk levels:",
            healthError
          );

        }


        /*
         * Current medications are optional in the
         * backend contract.
         *
         * We intentionally send an empty array when
         * the current patient UI does not provide a
         * medication list.
         */
        const currentMedications = [];


        /*
         * Call the REAL Ayurveda Herbal Recommendation
         * backend.
         */
        const result = await api.post(
          "/features/ayurveda/herbs",
          {
            diabetes_risk_level:
              diabetesRisk.toLowerCase(),

            cvd_risk_level:
              cvdRisk.toLowerCase(),

            primary_dosha:
              prakriti.primary_dosha.toLowerCase(),

            current_medications:
              currentMedications,
          }
        );


        /*
         * Backend response:
         *
         * {
         *   recommended_herbs: [],
         *   total_found: number,
         *   target_diseases: [],
         *   primary_dosha: string,
         *   safety_note: string,
         *   data_attribution: string
         * }
         */
        setHerbs(
          result?.recommended_herbs || []
        );

        setSafetyNote(
          result?.safety_note || ""
        );

        setDataAttribution(
          result?.data_attribution || ""
        );

      } catch (err) {

        console.error(
          "Failed to load herbal recommendations:",
          err
        );

        const message =
          err?.message ||
          "Unable to load personalized herbal recommendations.";

        setError(message);

        toast.error(message);

      } finally {

        setLoading(false);

      }

    };


    loadHerbalRecommendations();

  }, []);


  /*
   * Loading UI
   */
  if (loading) {

    return (
      <div>

        <PageHeader
          title="Botanical & Herbal Recommendations"
          description="Evidence-backed Ayurvedic botanical protocols synchronized with your health profile."
        />

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">

          {[1, 2, 3].map((item) => (

            <Card
              key={item}
              className="p-5"
            >

              <div className="animate-pulse space-y-4">

                <div className="h-10 w-10 rounded-xl bg-muted" />

                <div className="h-4 bg-muted rounded w-3/4" />

                <div className="h-3 bg-muted rounded w-full" />

                <div className="h-3 bg-muted rounded w-5/6" />

              </div>

            </Card>

          ))}

        </div>

      </div>
    );
  }


  /*
   * Error / missing Prakriti result
   */
  if (error) {

    return (
      <div>

        <PageHeader
          title="Botanical & Herbal Recommendations"
          description="Evidence-backed Ayurvedic botanical protocols synchronized with your health profile."
        />

        <Card>

          <CardContent className="p-8 text-center">

            <div
              className="
                mx-auto mb-4
                flex size-12
                items-center justify-center
                rounded-xl
                bg-amber-50
                text-amber-600
                dark:bg-amber-950/30
                dark:text-amber-400
              "
            >

              <AlertTriangle className="size-6" />

            </div>


            <h3 className="text-base font-bold">

              Herbal recommendations unavailable

            </h3>


            <p className="mt-2 text-sm text-muted-foreground">

              {error}

            </p>

          </CardContent>

        </Card>

      </div>
    );
  }


  return (
    <div>

      <PageHeader
        title="Botanical & Herbal Recommendations"
        description="Evidence-backed Ayurvedic botanical protocols synchronized with your health profile."
      />


      {/* Profile Summary */}

      <div className="mb-5">

        <Card>

          <CardContent className="p-4">

            <div className="flex items-center gap-3">

              <div
                className="
                  flex size-10
                  items-center justify-center
                  rounded-xl
                  bg-emerald-500/10
                  text-emerald-600
                "
              >

                <Sparkles className="size-5" />

              </div>


              <div>

                <p className="text-xs text-muted-foreground">
                  Personalized for
                </p>

                <p className="text-sm font-bold capitalize">
                  {herbs.length > 0 &&
                  herbs[0]?.for_doshas?.length
                    ? "Your Ayurvedic Constitution"
                    : "Your Health Profile"}
                </p>

              </div>

            </div>

          </CardContent>

        </Card>

      </div>


      {/* Herb Cards */}

      {herbs.length === 0 ? (

        <Card>

          <CardContent className="p-8 text-center">

            <Leaf className="size-8 mx-auto mb-3 text-emerald-600" />

            <h3 className="font-bold">
              No herbal recommendations found
            </h3>

            <p className="mt-2 text-sm text-muted-foreground">
              The recommendation engine did not find
              suitable herbs for the current health profile.
            </p>

          </CardContent>

        </Card>

      ) : (

        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">

          {herbs.map((herb, index) => {

            const warnings =
              herb.safety_warnings || [];

            const isSafe =
              herb.safe_to_use === true;


            return (
              <Card
                key={`${herb.scientific}-${index}`}
                className="
                  h-full
                  overflow-hidden
                  border-slate-200/70
                  bg-white
                  shadow-sm
                  dark:border-slate-800
                  dark:bg-slate-950
                "
              >

                <CardHeader className="pb-3">

                  <div className="flex items-start justify-between gap-3">

                    <div
                      className="
                        flex size-10 shrink-0
                        items-center justify-center
                        rounded-xl
                        bg-emerald-500/10
                        text-emerald-600
                      "
                    >

                      <span className="text-xl">
                        {herb.emoji || "🌿"}
                      </span>

                    </div>


                    {isSafe ? (

                      <Badge
                        variant="outline"
                        className="
                          border-emerald-200
                          bg-emerald-50
                          text-emerald-700
                          dark:border-emerald-900
                          dark:bg-emerald-950/30
                          dark:text-emerald-400
                        "
                      >

                        <ShieldCheck className="size-3 mr-1" />

                        Safety Checked

                      </Badge>

                    ) : (

                      <Badge
                        variant="outline"
                        className="
                          border-amber-200
                          bg-amber-50
                          text-amber-700
                          dark:border-amber-900
                          dark:bg-amber-950/30
                          dark:text-amber-400
                        "
                      >

                        <AlertTriangle className="size-3 mr-1" />

                        Caution

                      </Badge>

                    )}

                  </div>


                  <div className="pt-3">

                    <CardTitle className="text-sm font-bold">

                      {herb.name_en}

                    </CardTitle>


                    <p className="mt-1 text-xs italic text-muted-foreground">

                      {herb.scientific}

                    </p>


                    {herb.name_hi && (

                      <p className="mt-1 text-xs text-muted-foreground">

                        {herb.name_hi}

                      </p>

                    )}

                  </div>

                </CardHeader>


                <CardContent className="space-y-4">

                  {/* Evidence */}

                  <div>

                    <div className="flex items-center gap-2 mb-2">

                      <FlaskConical className="size-4 text-blue-500" />

                      <p className="text-xs font-bold">
                        Evidence
                      </p>

                    </div>


                    <div className="flex flex-wrap gap-2">

                      <Badge variant="secondary">

                        {herb.evidence_tier || "Unknown"}

                      </Badge>


                      {herb.pubmed_evidence
                        ?.evidence_quality && (

                        <Badge variant="outline">

                          PubMed:{" "}
                          {herb.pubmed_evidence.evidence_quality}

                        </Badge>

                      )}

                    </div>

                  </div>


                  {/* Purpose / Mechanism */}

                  {herb.mechanism && (

                    <div>

                      <p className="text-xs font-bold mb-1.5">
                        How it may help
                      </p>

                      <p className="text-[11px] leading-relaxed text-muted-foreground">

                        {herb.mechanism}

                      </p>

                    </div>

                  )}


                  {/* Dosage */}

                  {herb.dosage_en && (

                    <div
                      className="
                        rounded-xl
                        border
                        border-slate-200
                        bg-slate-50
                        p-3
                        dark:border-slate-800
                        dark:bg-slate-900/40
                      "
                    >

                      <p className="text-[10px] font-bold mb-1">

                        Traditional dosage information

                      </p>

                      <p className="text-[10px] leading-relaxed text-muted-foreground">

                        {herb.dosage_en}

                      </p>


                      {herb.timing && (

                        <p className="mt-1 text-[9px] text-muted-foreground">

                          Timing: {herb.timing}

                        </p>

                      )}

                    </div>

                  )}


                  {/* Safety warnings */}

                  {warnings.length > 0 && (

                    <div
                      className="
                        rounded-xl
                        border
                        border-amber-200
                        bg-amber-50/50
                        p-3
                        dark:border-amber-900
                        dark:bg-amber-950/20
                      "
                    >

                      <div className="flex items-center gap-2 mb-2">

                        <AlertTriangle className="size-3.5 text-amber-600" />

                        <p className="text-[10px] font-bold text-amber-700 dark:text-amber-400">

                          Safety warnings

                        </p>

                      </div>


                      <div className="space-y-1.5">

                        {warnings.map(
                          (warning, warningIndex) => (

                            <p
                              key={warningIndex}
                              className="
                                text-[9px]
                                leading-relaxed
                                text-amber-800
                                dark:text-amber-300
                              "
                            >

                              {warning}

                            </p>

                          )
                        )}

                      </div>

                    </div>

                  )}


                  {/* Disease relevance */}

                  {herb.for_diseases?.length > 0 && (

                    <div>

                      <p className="text-[10px] font-bold mb-2">

                        Relevant for

                      </p>


                      <div className="flex flex-wrap gap-1.5">

                        {herb.for_diseases.map(
                          (disease) => (

                            <Badge
                              key={disease}
                              variant="outline"
                              className="text-[9px]"
                            >

                              {disease}

                            </Badge>

                          )
                        )}

                      </div>

                    </div>

                  )}


                  {/* PubMed references */}

                  {herb.pubmed_evidence
                    ?.abstracts?.length > 0 && (

                    <div>

                      <p className="text-[10px] font-bold mb-2">

                        Research references

                      </p>


                      <div className="space-y-1.5">

                        {herb.pubmed_evidence.abstracts
                          .slice(0, 3)
                          .map((article) => (

                            <a
                              key={article.pmid}
                              href={article.url}
                              target="_blank"
                              rel="noreferrer"
                              className="
                                flex
                                items-start
                                gap-2
                                text-[9px]
                                text-blue-600
                                hover:underline
                                dark:text-blue-400
                              "
                            >

                              <ExternalLink className="size-3 shrink-0 mt-0.5" />

                              <span>
                                {article.title}
                              </span>

                            </a>

                          ))}

                      </div>

                    </div>

                  )}

                </CardContent>

              </Card>
            );
          })}

        </div>

      )}


      {/* Safety Note */}

      {safetyNote && (

        <Card className="mt-5">

          <CardContent className="p-4">

            <div className="flex items-start gap-3">

              <Info className="size-4 mt-0.5 shrink-0 text-amber-600" />

              <div>

                <p className="text-xs font-bold mb-1">
                  Important Safety Information
                </p>

                <p className="text-[10px] leading-relaxed text-muted-foreground">
                  {safetyNote}
                </p>

              </div>

            </div>

          </CardContent>

        </Card>

      )}


      {/* Data Attribution */}

      {dataAttribution && (

        <p className="mt-3 text-[9px] leading-relaxed text-muted-foreground">

          {dataAttribution}

        </p>

      )}

    </div>
  );
};


export default HerbalRecommendationsPage;