"""Production ML lifecycle for MediGuard AI."""

from __future__ import annotations

import json
import logging
import os
import shutil
import uuid
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import joblib
import numpy as np
import pandas as pd
import shap
import xgboost as xgb
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from ml.data_loader import FEATURE_COLUMNS, TARGET_COLUMNS, dataset_version, load_full_training_frame, validate_schema
from utils.config import settings

logger = logging.getLogger(__name__)

MODEL_ROOT = (Path(__file__).resolve().parents[1] / settings.model_dir).resolve()
BEST_MODEL_PATH = MODEL_ROOT / "best_model.pkl"
METADATA_PATH = MODEL_ROOT / "model_metadata.json"
VERSIONS_DIR = MODEL_ROOT / "versions"
DRIFT_THRESHOLD = float(os.getenv("DRIFT_THRESHOLD", "0.20"))
# Columns with this many distinct values or fewer are treated as categorical and
# excluded from PSI, which assumes a continuous distribution.
CATEGORICAL_MAX_UNIQUE = 4
# Set RETRAIN_ON_DRIFT=true to auto-retrain at startup. Default is off: startup
# should be fast and deterministic, and retraining is exposed at POST /predict/train.
RETRAIN_ON_DRIFT = os.getenv("RETRAIN_ON_DRIFT", "false").lower() == "true"

GENDER_MAP = {"female": 0, "male": 1, "other": 2, "f": 0, "m": 1}
ACTIVITY_MAP = {"sedentary": 0, "light": 1, "moderate": 2, "active": 3}

# XGBoost hyperparameters — logged as MLflow params on every training run.
XGB_PARAMS: Dict[str, Any] = {
    "n_estimators": 260,
    "max_depth": 5,
    "learning_rate": 0.08,
    "subsample": 0.9,
    "colsample_bytree": 0.9,
    "min_child_weight": 3,
    "reg_lambda": 1.0,
    "eval_metric": "logloss",
    "random_state": 42,
    "n_jobs": 1,
}


def _mlflow_set_tracking() -> bool:
    """Point mlflow at the project-wide sqlite backing store. Returns False (and
    logs, rather than raises) if mlflow itself can't be imported/configured, so
    training never hard-fails just because experiment tracking is unavailable."""
    try:
        import mlflow
        mlflow.set_tracking_uri(settings.mlflow_tracking_uri)
        mlflow.set_experiment(settings.mlflow_experiment_name)
        return True
    except Exception as exc:
        logger.warning("MLflow tracking unavailable, continuing without it: %s", exc)
        return False


def _risk_level(prob: float) -> str:
    if prob < 0.25:
        return "low"
    if prob < 0.50:
        return "moderate"
    if prob < 0.75:
        return "high"
    return "critical"


def _ensure_dirs() -> None:
    MODEL_ROOT.mkdir(parents=True, exist_ok=True)
    VERSIONS_DIR.mkdir(parents=True, exist_ok=True)


def _read_metadata() -> Dict[str, Any]:
    if METADATA_PATH.exists():
        return json.loads(METADATA_PATH.read_text())
    return {"best_version": None, "models": []}


def _write_metadata(metadata: Dict[str, Any]) -> None:
    _ensure_dirs()
    METADATA_PATH.write_text(json.dumps(metadata, indent=2))


def _next_version(metadata: Dict[str, Any]) -> str:
    existing = metadata.get("models", [])
    return f"v{len(existing) + 1}"


def _make_pipeline() -> Pipeline:
    """
    Builds the production classifier pipeline. Defaults to XGBoost.
    Set ML_ALGORITHM=random_forest to switch — see docs/MODEL_COMPARISON.md
    (generated by `python -m ml.baseline_comparison`), which found Random
    Forest edges out XGBoost on ROC-AUC/Recall on the currently-available
    2-of-3 Kaggle sources (n=214 validation rows). Left at xgboost by
    default rather than auto-promoted: that comparison should be re-run
    once the missing cardiovascular-disease-dataset source is added before
    treating the result as conclusive on this small a validation set.
    """
    algorithm = os.getenv("ML_ALGORITHM", "xgboost").lower()
    if algorithm == "random_forest":
        from sklearn.ensemble import RandomForestClassifier
        clf = RandomForestClassifier(
            n_estimators=300, max_depth=8, min_samples_leaf=3,
            class_weight="balanced", random_state=42, n_jobs=1,
        )
    elif algorithm == "logistic_regression":
        from sklearn.linear_model import LogisticRegression
        clf = LogisticRegression(max_iter=1000, class_weight="balanced", random_state=42)
    else:
        clf = xgb.XGBClassifier(**XGB_PARAMS)
    return Pipeline([
        ("scaler", StandardScaler()),
        ("clf", MultiOutputClassifier(clf, n_jobs=1)),
    ])


def _evaluate(pipeline: Pipeline, X_val: pd.DataFrame, y_val: pd.DataFrame) -> Dict[str, float]:
    probabilities = pipeline.predict_proba(X_val)
    predictions = pipeline.predict(X_val)
    metrics: Dict[str, float] = {}
    aucs = []
    accuracies = []
    precisions = []
    recalls = []
    for idx, target in enumerate(TARGET_COLUMNS):
        labels = y_val[target]
        probs = probabilities[idx][:, 1]
        pred = predictions[:, idx]
        auc = roc_auc_score(labels, probs) if labels.nunique() > 1 else 0.5
        acc = accuracy_score(labels, pred)
        precision = precision_score(labels, pred, zero_division=0)
        recall = recall_score(labels, pred, zero_division=0)
        metrics[f"{target}_auc"] = round(float(auc), 4)
        metrics[f"{target}_accuracy"] = round(float(acc), 4)
        metrics[f"{target}_precision"] = round(float(precision), 4)
        metrics[f"{target}_recall"] = round(float(recall), 4)
        metrics[f"{target}_f1"] = round(float(f1_score(labels, pred, zero_division=0)), 4)
        aucs.append(auc)
        accuracies.append(acc)
        precisions.append(precision)
        recalls.append(recall)
    metrics["auc_score"] = round(float(np.mean(aucs)), 4)
    metrics["accuracy"] = round(float(np.mean(accuracies)), 4)
    metrics["precision"] = round(float(np.mean(precisions)), 4)
    metrics["recall"] = round(float(np.mean(recalls)), 4)
    return metrics


def _feature_stats(df: pd.DataFrame) -> Dict[str, Dict[str, Any]]:
    """Capture the *actual* reference distribution for each feature.

    Previously this stored only mean/std and drift_report() re-simulated the
    reference as a Gaussian. For binary columns (gender_encoded, smoking,
    family_history_*) that produced nonsense PSI values in the 5-15 range, so
    drift was ALWAYS detected and the model retrained on every single startup.
    We now persist the real binned reference proportions instead.
    """
    stats: Dict[str, Dict[str, Any]] = {}
    for col in FEATURE_COLUMNS:
        series = pd.to_numeric(df[col], errors="coerce").dropna()
        n_unique = int(series.nunique())
        is_categorical = n_unique <= CATEGORICAL_MAX_UNIQUE

        quantiles = np.unique(np.percentile(series, np.linspace(0, 100, 11))).tolist()
        if len(quantiles) < 2:
            quantiles = [float(series.min()) - 1e-6, float(series.max()) + 1e-6]
        quantiles[0] -= 1e-6
        quantiles[-1] += 1e-6

        ref_counts = np.histogram(series.to_numpy(), bins=quantiles)[0]
        ref_pct = (ref_counts / max(ref_counts.sum(), 1)).tolist()

        stats[col] = {
            "mean": float(series.mean()),
            "std": float(series.std() or 1.0),
            "quantiles": quantiles,
            "reference_pct": ref_pct,
            "n_unique": n_unique,
            "categorical": is_categorical,
        }
    return stats


def _psi(reference: np.ndarray, current: np.ndarray, bins: List[float]) -> float:
    eps = 1e-6
    ref_counts = np.histogram(reference, bins=bins)[0]
    cur_counts = np.histogram(current, bins=bins)[0]
    ref_pct = np.clip(ref_counts / max(ref_counts.sum(), 1), eps, None)
    cur_pct = np.clip(cur_counts / max(cur_counts.sum(), 1), eps, None)
    return float(np.sum((cur_pct - ref_pct) * np.log(cur_pct / ref_pct)))


def _psi_from_reference(ref_pct: np.ndarray, current: np.ndarray, bins: List[float]) -> float:
    """PSI against the stored training-time bin proportions."""
    eps = 1e-6
    cur_counts = np.histogram(current, bins=bins)[0]
    cur_pct = np.clip(cur_counts / max(cur_counts.sum(), 1), eps, None)
    ref = np.clip(np.asarray(ref_pct, dtype=float), eps, None)
    if len(ref) != len(cur_pct):
        return 0.0
    return float(np.sum((cur_pct - ref) * np.log(cur_pct / ref)))


class MediGuardMLModel:
    def __init__(self) -> None:
        self.pipeline: Optional[Pipeline] = None
        self.model_version = "unloaded"
        self.metadata: Dict[str, Any] = {}
        self.load_best_model()

    def load_best_model(self) -> bool:
        _ensure_dirs()
        if not BEST_MODEL_PATH.exists():
            return False
        bundle = joblib.load(BEST_MODEL_PATH)
        self.pipeline = bundle["pipeline"]
        self.model_version = bundle["version"]
        self.metadata = bundle.get("metadata", {})
        logger.info("Loaded best MediGuard model %s from %s", self.model_version, BEST_MODEL_PATH)
        return True

    def ensure_ready(self) -> None:
        if self.pipeline is not None:
            return
        raise RuntimeError(
            "No trained model found. Use POST /api/v1/predict/train after placing Kaggle CSVs in backend/data/raw."
        )

    def train(self, X: pd.DataFrame | None = None, y: pd.DataFrame | None = None, force_replace: bool = False) -> Dict[str, Any]:
        _ensure_dirs()
        if X is None or y is None:
            full = load_full_training_frame()
            X = full[FEATURE_COLUMNS]
            y = full[TARGET_COLUMNS]
        else:
            full = validate_schema(pd.concat([X.reset_index(drop=True), y.reset_index(drop=True)], axis=1))
            X = full[FEATURE_COLUMNS]
            y = full[TARGET_COLUMNS]

        X_train, X_val, y_train, y_val = train_test_split(
            X,
            y,
            test_size=0.20,
            random_state=42,
            stratify=(y["diabetes_label"].astype(str) + "_" + y["cardiovascular_label"].astype(str)
                      + "_" + y["hypertension_label"].astype(str)),
        )
        candidate = _make_pipeline()
        candidate.fit(X_train, y_train)
        metrics = _evaluate(candidate, X_val, y_val)

        registry = _read_metadata()
        best = next((m for m in registry.get("models", []) if m["version"] == registry.get("best_version")), None)
        candidate_score = metrics["auc_score"]
        best_score = float(best.get("auc_score", -1)) if best else -1
        should_replace = force_replace or best is None or candidate_score >= best_score

        version = _next_version(registry)
        version_path = VERSIONS_DIR / f"{version}.pkl"
        metadata = {
            "version": version,
            "trained_at": datetime.utcnow().isoformat(),
            "accuracy": metrics["accuracy"],
            "auc_score": metrics["auc_score"],
            "training_dataset_version": dataset_version(full),
            "features": FEATURE_COLUMNS,
            "targets": TARGET_COLUMNS,
            "n_samples": int(len(full)),
            "drift_threshold": DRIFT_THRESHOLD,
            "feature_stats": _feature_stats(full[FEATURE_COLUMNS]),
            "source_policy": "Kaggle only",
            "model_type": "xgboost_multioutput",
        }
        bundle = {"pipeline": candidate, "version": version, "metadata": metadata}
        joblib.dump(bundle, version_path)

        mlflow_run_id = self._log_to_mlflow(candidate, version, metrics, metadata)
        metadata["mlflow_run_id"] = mlflow_run_id

        registry.setdefault("models", []).append({**metadata, **metrics, "path": str(version_path)})
        if should_replace:
            shutil.copyfile(version_path, BEST_MODEL_PATH)
            registry["best_version"] = version
            self.pipeline = candidate
            self.model_version = version
            self.metadata = metadata
            decision = "promoted"
        else:
            self.load_best_model()
            decision = "kept_existing_best"

        registry["updated_at"] = datetime.utcnow().isoformat()
        _write_metadata(registry)
        return {"version": version, "decision": decision, "mlflow_run_id": mlflow_run_id, **metrics, "best_version": registry.get("best_version")}

    def _log_to_mlflow(
        self, pipeline: Pipeline, version: str, metrics: Dict[str, float], metadata: Dict[str, Any]
    ) -> Optional[str]:
        """Log the training run to MLflow. Never raises: a broken MLflow backend
        must not prevent a model from training and being promoted."""
        if not _mlflow_set_tracking():
            return None
        try:
            import mlflow
            import mlflow.sklearn

            with mlflow.start_run(run_name=f"mediguard-{version}") as run:
                mlflow.log_param("version", version)
                mlflow.log_param("model_type", metadata["model_type"])
                mlflow.log_param("n_samples", metadata["n_samples"])
                mlflow.log_param("training_dataset_version", metadata["training_dataset_version"])
                for key, value in XGB_PARAMS.items():
                    mlflow.log_param(f"xgb_{key}", value)
                for key, value in metrics.items():
                    mlflow.log_metric(key, value)
                mlflow.sklearn.log_model(
                    pipeline,
                    artifact_path="model",
                    # mlflow's default sklearn-flavor serializer (skops) rejects
                    # XGBoost's Booster as an "untrusted type" as of mlflow 3.x's
                    # stricter security defaults. Cloudpickle has no such
                    # allowlist and matches the joblib/pickle-based persistence
                    # already used for the versioned .pkl files, so this is the
                    # more consistent choice, not just a compatibility shim.
                    serialization_format="cloudpickle",
                )
                mlflow.log_dict(metadata, "metadata.json")
                logger.info("Logged MLflow run %s for model version %s", run.info.run_id, version)
                return run.info.run_id
        except Exception as exc:
            logger.warning("MLflow logging failed for version %s: %s", version, exc)
            return None

    def drift_report(self, current: pd.DataFrame | List[Dict[str, Any]] | None = None) -> Dict[str, Any]:
        self.ensure_ready()
        if current is None:
            current_df = load_full_training_frame()[FEATURE_COLUMNS]
        elif isinstance(current, pd.DataFrame):
            current_df = current[FEATURE_COLUMNS].copy()
        else:
            current_df = pd.DataFrame(current)[FEATURE_COLUMNS].copy()

        feature_drifts: Dict[str, float] = {}
        max_psi = 0.0
        stats = self.metadata.get("feature_stats", {})
        skipped: List[str] = []
        for col in FEATURE_COLUMNS:
            if col not in stats:
                continue
            if stats[col].get("categorical"):
                skipped.append(col)
                continue
            ref_pct = stats[col].get("reference_pct")
            if not ref_pct:
                # Model trained before this fix — no stored reference. Skip
                # rather than fabricate one from a Gaussian.
                skipped.append(col)
                continue
            cur = pd.to_numeric(current_df[col], errors="coerce").dropna().to_numpy()
            if len(cur) < 10:
                continue
            psi = _psi_from_reference(np.asarray(ref_pct), cur, stats[col]["quantiles"])
            feature_drifts[col] = round(psi, 4)
            max_psi = max(max_psi, psi)
        drift = max_psi > DRIFT_THRESHOLD
        return {
            "run_id": str(uuid.uuid4()),
            "dataset_size": int(len(current_df)),
            "psi_score": round(max_psi, 4),
            "drift_detected": drift,
            "feature_drifts": feature_drifts,
            "skipped_features": skipped,
            "recommendation": "Retrain and compare candidate model" if drift else "No retraining required",
        }

    def train_if_needed(self) -> Dict[str, Any]:
        if self.load_best_model():
            try:
                report = self.drift_report()
            except Exception as exc:
                logger.warning("Drift check skipped: %s", exc)
                return {"action": "loaded_best_model", "version": self.model_version, "drift": None}
            if report["drift_detected"] and RETRAIN_ON_DRIFT:
                metrics = self.train()
                return {"action": "drift_retrain", "drift": report, "training": metrics}
            if report["drift_detected"]:
                logger.warning(
                    "Drift detected (PSI=%.4f) but RETRAIN_ON_DRIFT is off. "
                    "Call POST /api/v1/predict/train to retrain.", report["psi_score"],
                )
            return {"action": "loaded_best_model", "version": self.model_version, "drift": report}
        metrics = self.train(force_replace=True)
        return {"action": "initial_training", "training": metrics}

    def _encode_patient(self, raw: Dict[str, Any]) -> pd.DataFrame:
        row = {
            "age": raw["age"],
            "gender_encoded": GENDER_MAP.get(str(raw.get("gender", "male")).lower(), 1),
            "bmi": raw["bmi"],
            "blood_pressure_systolic": raw["blood_pressure_systolic"],
            "blood_pressure_diastolic": raw["blood_pressure_diastolic"],
            "fasting_glucose": raw["fasting_glucose"],
            "hba1c": raw["hba1c"],
            "cholesterol_total": raw["cholesterol_total"],
            "cholesterol_hdl": raw["cholesterol_hdl"],
            "cholesterol_ldl": raw["cholesterol_ldl"],
            "triglycerides": raw["triglycerides"],
            "smoking": int(bool(raw.get("smoking", False))),
            "family_history_diabetes": int(bool(raw.get("family_history_diabetes", False))),
            "family_history_cvd": int(bool(raw.get("family_history_cvd", False))),
            "physical_activity_encoded": ACTIVITY_MAP.get(str(raw.get("physical_activity", "moderate")).lower(), 2),
        }
        return pd.DataFrame([row], columns=FEATURE_COLUMNS)

    def predict(self, patient: Dict[str, Any]) -> Dict[str, Any]:
        self.ensure_ready()
        X = self._encode_patient(patient)
        X_scaled = self.pipeline.named_steps["scaler"].transform(X)
        X_scaled_df = pd.DataFrame(X_scaled, columns=FEATURE_COLUMNS)
        proba_list = self.pipeline.predict_proba(X)
        dia_prob = float(proba_list[0][0, 1])
        cvd_prob = float(proba_list[1][0, 1])
        htn_prob = float(proba_list[2][0, 1])

        def shap_explain(target_idx: int, prob: float) -> List[Dict[str, Any]]:
            estimator = self.pipeline.named_steps["clf"].estimators_[target_idx]
            raw_values = X.iloc[0].to_dict()
            try:
                explainer = shap.TreeExplainer(estimator)
                explanation = explainer(X_scaled_df)
                shap_values = explanation.values[0]
            except Exception as exc:
                logger.warning("SHAP explanation failed, falling back to feature_importances_: %s", exc)
                importances = estimator.feature_importances_
                shap_values = importances * (prob - 0.5)
            ranked = sorted(
                zip(FEATURE_COLUMNS, shap_values), key=lambda item: abs(item[1]), reverse=True
            )[:8]
            return [
                {
                    "feature": name,
                    "value": float(raw_values[name]),
                    "shap_value": round(float(value), 4),
                    "impact": "increases risk" if value >= 0 else "decreases risk",
                }
                for name, value in ranked
            ]

        return {
            "prediction_id": str(uuid.uuid4()),
            "timestamp": datetime.utcnow().isoformat(),
            "model_version": self.model_version,
            "training_data": "Kaggle datasets only",
            "diabetes": {
                "probability": round(dia_prob, 4),
                "risk_level": _risk_level(dia_prob),
                "confidence": round(1.0 - abs(dia_prob - 0.5), 4),
                "shap_features": shap_explain(0, dia_prob),
            },
            "cardiovascular": {
                "probability": round(cvd_prob, 4),
                "risk_level": _risk_level(cvd_prob),
                "confidence": round(1.0 - abs(cvd_prob - 0.5), 4),
                "shap_features": shap_explain(1, cvd_prob),
            },
            "hypertension": {
                "probability": round(htn_prob, 4),
                "risk_level": _risk_level(htn_prob),
                "confidence": round(1.0 - abs(htn_prob - 0.5), 4),
                "shap_features": shap_explain(2, htn_prob),
            },
            "combined_risk_score": round((dia_prob + cvd_prob + htn_prob) / 3, 4),
        }


_model_instance: Optional[MediGuardMLModel] = None


def get_model() -> MediGuardMLModel:
    global _model_instance
    if _model_instance is None:
        _model_instance = MediGuardMLModel()
    return _model_instance
